schema_version: "1.0"
default_process: "adaptive"
sop:
  - id: "feature-implementation"
    name: "Feature Implementation"
    trigger: "User requests new feature or code change"
    steps:
      - id: "analyze"
        action: "Analyze requirements and existing code"
        tool: "file_manager"
        on_success: "plan"
        on_failure: "clarify"
        timeout: 30
      - id: "plan"
        action: "Create implementation plan"
        tool: null
        on_success: "implement"
        on_failure: "understand"
        timeout: 60
      - id: "implement"
        action: "Write minimal implementation"
        tool: "code_executor"
        on_success: "verify"
        on_failure: "implement"
        timeout: 120
      - id: "verify"
        action: "Run tests, lint, type check"
        tool: "code_executor"
        on_success: "commit"
        on_failure: "implement"
        timeout: 60
      - id: "commit"
        action: "Commit changes"
        tool: "git"
        on_failure: "verify"
        timeout: 30
handoffs:
  - from: "senior-python-dev"
    to: "qa-engineer"
    condition: "Complex testing scenario required"
    context_transfer: ["requirements", "implementation_notes", "test_plan"]
reporting:
  format: "structured"
