# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from vasini.agent.v1 import agent_pb2 as vasini_dot_agent_dot_v1_dot_agent__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vasini/agent/v1/agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunAgent = channel.unary_stream(
                '/vasini.agent.v1.AgentService/RunAgent',
                request_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentRequest.SerializeToString,
                response_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentResponse.FromString,
                _registered_method=True)
        self.GetAgentStatus = channel.unary_unary(
                '/vasini.agent.v1.AgentService/GetAgentStatus',
                request_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.GetAgentStatusRequest.SerializeToString,
                response_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.AgentStatus.FromString,
                _registered_method=True)
        self.CancelAgent = channel.unary_unary(
                '/vasini.agent.v1.AgentService/CancelAgent',
                request_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentRequest.SerializeToString,
                response_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RunAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAgentStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunAgent': grpc.unary_stream_rpc_method_handler(
                    servicer.RunAgent,
                    request_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentRequest.FromString,
                    response_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentResponse.SerializeToString,
            ),
            'GetAgentStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAgentStatus,
                    request_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.GetAgentStatusRequest.FromString,
                    response_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.AgentStatus.SerializeToString,
            ),
            'CancelAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelAgent,
                    request_deserializer=vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentRequest.FromString,
                    response_serializer=vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vasini.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vasini.agent.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RunAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vasini.agent.v1.AgentService/RunAgent',
            vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentRequest.SerializeToString,
            vasini_dot_agent_dot_v1_dot_agent__pb2.RunAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAgentStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasini.agent.v1.AgentService/GetAgentStatus',
            vasini_dot_agent_dot_v1_dot_agent__pb2.GetAgentStatusRequest.SerializeToString,
            vasini_dot_agent_dot_v1_dot_agent__pb2.AgentStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vasini.agent.v1.AgentService/CancelAgent',
            vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentRequest.SerializeToString,
            vasini_dot_agent_dot_v1_dot_agent__pb2.CancelAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
